#include "installer.h"

#include <stddef.h>
#include <stdint.h>
#include <limine-bios-hdd.h>

#include "drivers/storage/ide/ide.h"
#include "fs/fat32/directory/directory.h"
#include "fs/fat32/file/file.h"
#include "fs/fat32/vbr/vbr.h"
#include "fs/iso9660/iso9660.h"
#include "fs/partition/mbr/mbr.h"
#include "kernel/debug/debug.h"
#include "kernel/terminal/terminal.h"
#include "lib/string/string.h"
#include "vendor/limine/limine.h"

#define INSTALLER_STAGE2_LOCATION_OFFSET 0x1a4U

__attribute__((used, section(".requests")))
static volatile struct limine_executable_cmdline_request CommandLineRequest = {
    .id = LIMINE_EXECUTABLE_CMDLINE_REQUEST, .revision = 0
};

typedef struct
{
    IDEDevice SourceDevice;
    IDEDevice TargetDevice;
    ISO9660File SourceFile;
    uint8_t CachedBlock[ISO9660_LOGICAL_BLOCK_SIZE];
    uint32_t CachedBlockIndex;
    bool CacheValid;
} InstallerFileSource;

static const char *InstallerCommandLine(void)
{
    return CommandLineRequest.response != NULL &&
           CommandLineRequest.response->cmdline != NULL ?
           CommandLineRequest.response->cmdline : "";
}

bool InstallerBootRequested(void)
{
    return strcmp(InstallerCommandLine(), "mode=install debug=verbose") == 0;
}

bool InstallerCommandAvailable(void)
{
    return strcmp(InstallerCommandLine(), "mode=live debug=verbose") == 0;
}

static INSTALLER_STATUS InstallerFail(INSTALLER_STATUS Status, const char *Message)
{
    TerminalPrintLine32(Message, 0x00ff5c77U);
    DbgErr(Message, (uintptr_t)InstallerRun);
    return Status;
}

static void InstallerProgress(const char *Message)
{
    TerminalPrintLine32(Message, 0x00e9f1ffU);
    DbgInfo(Message, (uintptr_t)InstallerRun);
}

static void InstallerWriteLittleEndian64(uint8_t *Output, uint64_t Value)
{
    for (uint32_t Index = 0; Index < 8U; Index++)
        Output[Index] = (uint8_t)(Value >> (Index * 8U));
}

/* Writes Limine's stage 1 MBR and stage 2 in the post-MBR gap. */
static bool InstallerInstallLimineBIOS(const MBR *PartitionTable)
{
    uint8_t Sector[IDE_SECTOR_SIZE];
    uint32_t ImageSize = (uint32_t)sizeof(binary_limine_hdd_bin_data);
    uint32_t Stage2Sectors = (ImageSize - IDE_SECTOR_SIZE + IDE_SECTOR_SIZE - 1U) /
                             IDE_SECTOR_SIZE;

    if (PartitionTable == NULL || ImageSize <= IDE_SECTOR_SIZE ||
        Stage2Sectors >= PartitionTable->Partitions[0].StartLBA) return false;

    memcpy(Sector, binary_limine_hdd_bin_data, IDE_SECTOR_SIZE);
    InstallerWriteLittleEndian64(&Sector[INSTALLER_STAGE2_LOCATION_OFFSET],
                                 (uint64_t)IDE_SECTOR_SIZE);
    /* Keep the partition table generated by the MBR layer intact. */
    memcpy(&Sector[446], PartitionTable->Partitions,
           sizeof(PartitionTable->Partitions));
    Sector[510] = 0x55U;
    Sector[511] = 0xaaU;
    if (!IDEWriteSector(0U, Sector)) return false;
    for (uint32_t Index = 0; Index < Stage2Sectors; Index++)
    {
        uint32_t Offset = IDE_SECTOR_SIZE + Index * IDE_SECTOR_SIZE;
        uint32_t Remaining = ImageSize - Offset;
        memset(Sector, 0, sizeof(Sector));
        if (Remaining > IDE_SECTOR_SIZE) Remaining = IDE_SECTOR_SIZE;
        memcpy(Sector, &binary_limine_hdd_bin_data[Offset], Remaining);
        if (!IDEWriteSector(1U + Index, Sector)) return false;
    }
    return true;
}

static bool InstallerPreparePartition(const IDEDevice *TargetDevice,
                                       MBR *PartitionTable)
{
    if (TargetDevice == NULL || PartitionTable == NULL ||
        !IDESelectDevice(TargetDevice)) return false;

    /* Reuse an existing FAT32 partition when it is large enough. */
    if (MBRRead(PartitionTable) && MBRIsValid(PartitionTable))
    {
        for (uint32_t Index = 0; Index < 4U; Index++)
        {
            const MBRPartitionEntry *Partition =
                MBRGetPartition(PartitionTable, (uint8_t)Index);
            if (Partition != NULL &&
                (Partition->PartitionType == 0x0bU ||
                 Partition->PartitionType == 0x0cU) &&
                Partition->StartLBA >= 2048U && Partition->SectorCount >=
                65525U * 8U)
            {
                return true;
            }
        }
    }

    return MBRCreateSingleFAT32(TargetDevice->SectorCount, PartitionTable);
}

/* Reads source bytes through ISO9660 and restores the selected target disk. */
static bool InstallerReadISOFile(void *Context, uint32_t ByteOffset,
                                 void *Buffer, uint32_t ByteCount)
{
    InstallerFileSource *Source = (InstallerFileSource *)Context;
    uint8_t *Output = (uint8_t *)Buffer;

    if (Source == NULL || Buffer == NULL ||
        ByteOffset > Source->SourceFile.DataLength ||
        ByteCount > Source->SourceFile.DataLength - ByteOffset) return false;

    while (ByteCount != 0U)
    {
        uint32_t BlockIndex = ByteOffset / ISO9660_LOGICAL_BLOCK_SIZE;
        uint32_t BlockOffset = ByteOffset % ISO9660_LOGICAL_BLOCK_SIZE;
        uint32_t CopySize = ISO9660_LOGICAL_BLOCK_SIZE - BlockOffset;
        uint32_t ValidBytes;

        if (CopySize > ByteCount) CopySize = ByteCount;
        if (!Source->CacheValid || Source->CachedBlockIndex != BlockIndex)
        {
            if (!IDESelectDevice(&Source->SourceDevice) ||
                !ISO9660ReadFileSector(&Source->SourceFile, BlockIndex,
                                       Source->CachedBlock, &ValidBytes) ||
                BlockOffset + CopySize > ValidBytes)
            {
                IDESelectDevice(&Source->TargetDevice);
                return false;
            }
            Source->CachedBlockIndex = BlockIndex;
            Source->CacheValid = true;
        }
        memcpy(Output, &Source->CachedBlock[BlockOffset], CopySize);
        Output += CopySize;
        ByteOffset += CopySize;
        ByteCount -= CopySize;
    }
    return IDESelectDevice(&Source->TargetDevice);
}

static bool InstallerCopyFile(const IDEDevice *SourceDevice,
                              const IDEDevice *TargetDevice,
                              const ISO9660File *SourceFile,
                              FAT32Directory *TargetDirectory,
                              const char *TargetName)
{
    InstallerFileSource Source;

    if (SourceDevice == NULL || TargetDevice == NULL || SourceFile == NULL ||
        TargetDirectory == NULL || TargetName == NULL) return false;
    Source.SourceDevice = *SourceDevice;
    Source.TargetDevice = *TargetDevice;
    Source.SourceFile = *SourceFile;
    Source.CachedBlockIndex = 0U;
    Source.CacheValid = false;
    return IDESelectDevice(TargetDevice) &&
           FAT32FileWriteFromReader(TargetDirectory, TargetName,
                                   SourceFile->DataLength, InstallerReadISOFile,
                                   &Source) &&
           FAT32FileVerifyFromReader(TargetDirectory, TargetName,
                                     SourceFile->DataLength, InstallerReadISOFile,
                                     &Source);
}

INSTALLER_STATUS InstallerRun(void)
{
    IDEDevice SourceDevice, TargetDevice;
    ISO9660Volume ISO;
    ISO9660Directory Root, Boot, Limine;
    ISO9660File Kernel, LimineSystem, LimineConfig;
    MBR PartitionTable;
    FAT32BootSector FATBoot;
    FAT32Directory FATRoot, FATBootDirectory, FATLimineDirectory;

    TerminalClear32(0x00000000U);
    TerminalPrintLine32("NULLOS IN-KERNEL INSTALLER", 0x00d7e8ffU);
    InstallerProgress("1/10 Detecting IDE ATA and ATAPI devices...");
    if (!IDEInitialize() || !IDEGetDevice(IDE_DEVICE_ATA, 0U, &TargetDevice))
        return InstallerFail(INSTALLER_STATUS_NO_TARGET_DISK,
                             "INSTALL ERROR: no writable ATA disk detected.");
    if (!IDEGetDevice(IDE_DEVICE_ATAPI, 0U, &SourceDevice))
        return InstallerFail(INSTALLER_STATUS_NO_INSTALLATION_MEDIA,
                             "INSTALL ERROR: no ATAPI installation CD detected.");

    InstallerProgress("2/10 Mounting installation ISO9660 media...");
    if (!IDESelectDevice(&SourceDevice) || !ISO9660OpenVolume(&ISO, 0U) ||
        !ISO9660ReadRootDirectory(&ISO, &Root) ||
        !ISO9660FindDirectory(&Root, "boot", &Boot) ||
        !ISO9660FindDirectory(&Boot, "limine", &Limine) ||
        !ISO9660FindFile(&Boot, "kernel.elf", &Kernel) ||
        !ISO9660FindFile(&Limine, "limine-bios.sys", &LimineSystem) ||
        !ISO9660FindFile(&Limine, "limine.conf", &LimineConfig))
        return InstallerFail(INSTALLER_STATUS_ISO_MOUNT_FAILED,
                             "INSTALL ERROR: installation ISO is invalid or incomplete.");

    InstallerProgress("3/10 Creating MBR FAT32 installation partition...");
    if (!InstallerPreparePartition(&TargetDevice, &PartitionTable))
        return InstallerFail(INSTALLER_STATUS_PARTITION_FAILED,
                             "INSTALL ERROR: target disk is too small for FAT32.");
    InstallerProgress("4/10 Installing Limine BIOS stage 1 and stage 2...");
    if (!InstallerInstallLimineBIOS(&PartitionTable))
        return InstallerFail(INSTALLER_STATUS_BOOTLOADER_FAILED,
                             "INSTALL ERROR: failed to write Limine BIOS stages.");
    InstallerProgress("5/10 Formatting target partition as FAT32...");
    if (!FAT32Format(PartitionTable.Partitions[0].StartLBA,
                     PartitionTable.Partitions[0].SectorCount, &FATBoot) ||
        !FAT32DirectoryOpenRoot(&FATRoot, &FATBoot,
                                PartitionTable.Partitions[0].StartLBA) ||
        !FAT32DirectoryCreateDirectory(&FATRoot, "boot", &FATBootDirectory) ||
        !FAT32DirectoryCreateDirectory(&FATBootDirectory, "limine",
                                       &FATLimineDirectory))
        return InstallerFail(INSTALLER_STATUS_FORMAT_FAILED,
                             "INSTALL ERROR: FAT32 format or directory setup failed.");

    InstallerProgress("6/10 Copying and verifying kernel.elf...");
    if (!InstallerCopyFile(&SourceDevice, &TargetDevice, &Kernel,
                           &FATBootDirectory, "kernel.elf"))
        return InstallerFail(INSTALLER_STATUS_COPY_FAILED,
                             "INSTALL ERROR: kernel.elf copy or verification failed.");
    InstallerProgress("7/10 Copying and verifying limine-bios.sys...");
    if (!InstallerCopyFile(&SourceDevice, &TargetDevice, &LimineSystem,
                           &FATLimineDirectory, "limine-bios.sys"))
        return InstallerFail(INSTALLER_STATUS_COPY_FAILED,
                             "INSTALL ERROR: limine-bios.sys copy or verification failed.");
    InstallerProgress("8/10 Copying and verifying limine.conf...");
    if (!InstallerCopyFile(&SourceDevice, &TargetDevice, &LimineConfig,
                           &FATLimineDirectory, "limine.conf"))
        return InstallerFail(INSTALLER_STATUS_COPY_FAILED,
                             "INSTALL ERROR: limine.conf copy or verification failed.");
    InstallerProgress("9/10 Writing and verifying partition table...");
    if (!MBRWrite(&PartitionTable) || !MBRRead(&PartitionTable) ||
        !MBRIsValid(&PartitionTable))
        return InstallerFail(INSTALLER_STATUS_VERIFY_FAILED,
                             "INSTALL ERROR: MBR verification failed.");
    InstallerProgress("10/10 Installation complete. Remove ISO and boot disk.");
    return INSTALLER_STATUS_SUCCESS;
}

INSTALLER_STATUS InstallerRunPreflight(void)
{
    return InstallerRun();
}
