#ifndef NULLOS_INSTALLER_H
#define NULLOS_INSTALLER_H

#include <stdbool.h>

typedef enum
{
    INSTALLER_STATUS_SUCCESS = 0,
    INSTALLER_STATUS_NO_TARGET_DISK,
    INSTALLER_STATUS_NO_INSTALLATION_MEDIA,
    INSTALLER_STATUS_ISO_MOUNT_FAILED,
    INSTALLER_STATUS_SOURCE_FILE_MISSING,
    INSTALLER_STATUS_PARTITION_FAILED,
    INSTALLER_STATUS_BOOTLOADER_FAILED,
    INSTALLER_STATUS_FORMAT_FAILED,
    INSTALLER_STATUS_DIRECTORY_FAILED,
    INSTALLER_STATUS_COPY_FAILED,
    INSTALLER_STATUS_VERIFY_FAILED
} INSTALLER_STATUS;

bool InstallerBootRequested(void);
bool InstallerCommandAvailable(void);
INSTALLER_STATUS InstallerRun(void);
INSTALLER_STATUS InstallerRunPreflight(void);

#endif
